channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=25.0.1
- pip:
  - mlflow==2.21.2
  - attrs==25.1.0
  - cloudpickle==3.1.1
  - defusedxml==0.7.1
  - ipython==8.18.1
  - matplotlib==3.9.4
  - more-itertools==10.6.0
  - numpy==2.0.2
  - opencv-python==4.11.0.86
  - pandas==2.2.3
  - psutil==7.0.0
  - pydot==3.0.4
  - scikit-learn==1.6.1
  - scipy==1.13.1
  - tensorflow-intel==2.18.0
name: mlflow-env
